# Generated by Django 3.1.4 on 2021-01-24 11:38

from django.db import migrations, models
import veems.channel.models
import veems.common.fields
import veems.common.validators
import veems.media.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', veems.common.fields.ShortUUIDField(default=veems.common.fields._default, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_on', models.DateTimeField(db_index=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=60)),
                ('description', models.TextField(max_length=5000)),
                ('sync_videos_interested', models.BooleanField(db_index=True)),
                ('language', models.CharField(default=None, max_length=2, validators=[veems.common.validators.validate_language])),
                ('avatar_image', models.ImageField(storage=veems.media.storage_backends.MediaStorage, upload_to=veems.channel.models._channel_avatar_image_upload_to)),
                ('banner_image', models.ImageField(blank=True, null=True, storage=veems.media.storage_backends.MediaStorage, upload_to=veems.channel.models._channel_banner_image_upload_to)),
                ('is_selected', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['created_on'],
                'abstract': False,
            },
        ),
    ]
