# Generated by Django 3.1.4 on 2020-12-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='visibility',
        ),
        migrations.AddField(
            model_name='channel',
            name='sync_videos_interested',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
