# Generated by Django 3.1.4 on 2021-01-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_channel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
