# Generated by Django 3.1.4 on 2021-02-04 19:33

from django.db import migrations, models
import veems.channel.models
import veems.media.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_auto_20210128_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='avatar_image',
            field=models.ImageField(
                blank=True,
                null=True,
                storage=veems.media.storage_backends.MediaStorage,
                upload_to=veems.channel.models._channel_avatar_image_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name='channel',
            name='deleted_on',
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
    ]
