# Generated by Django 3.1.6 on 2021-02-23 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0005_auto_20210204_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['-created_on']},
        ),
    ]
