# Generated by Django 3.1.4 on 2021-01-05 21:54

from django.db import migrations, models
import veems.channel.models
import veems.media.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0005_auto_20210102_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='avatar_image',
            field=models.ImageField(
                null=True,
                storage=veems.media.storage_backends.MediaStorage,
                upload_to=veems.channel.models._channel_avatar_image_upload_to,
            ),
        ),
        migrations.AddField(
            model_name='channel',
            name='banner_image',
            field=models.ImageField(
                null=True,
                storage=veems.media.storage_backends.MediaStorage,
                upload_to=veems.channel.models._channel_banner_image_upload_to,
            ),
        ),
    ]
