# Generated by Django 3.1.7 on 2021-04-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0006_auto_20210223_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='sync_videos_interested',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
