# Generated by Django 3.1.4 on 2021-01-10 21:45

from django.db import migrations, models
import veems.channel.models
import veems.media.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0006_auto_20210105_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='channel',
            name='avatar_image',
            field=models.ImageField(
                default=False,
                storage=veems.media.storage_backends.MediaStorage,
                upload_to=veems.channel.models._channel_avatar_image_upload_to,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel',
            name='banner_image',
            field=models.ImageField(
                blank=True,
                null=True,
                storage=veems.media.storage_backends.MediaStorage,
                upload_to=veems.channel.models._channel_banner_image_upload_to,
            ),
        ),
    ]
