# Generated by Django 3.1.4 on 2021-01-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0007_auto_20210110_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='is_selected',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(db_index=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='channel',
            name='sync_videos_interested',
            field=models.BooleanField(db_index=True),
        ),
    ]
