# Generated by Django 3.1.7 on 2021-05-04 18:42

from django.db import migrations, models
import veems.channel.models
import veems.media.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0007_auto_20210418_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='avatar_image',
            field=models.ImageField(
                blank=True,
                null=True,
                storage=veems.media.storage_backends.MediaStorage,
                upload_to=veems.channel.models._channel_avatar_image_upload_to,
                validators=[
                    veems.channel.models._validate_minimum_size_avatar_image
                ],
                verbose_name='Avatar Image',
            ),
        ),
        migrations.AlterField(
            model_name='channel',
            name='banner_image',
            field=models.ImageField(
                blank=True,
                null=True,
                storage=veems.media.storage_backends.MediaStorage,
                upload_to=veems.channel.models._channel_banner_image_upload_to,
                validators=[
                    veems.channel.models._validate_minimum_size_banner_image
                ],
                verbose_name='Banner Image',
            ),
        ),
    ]
