# Generated by Django 3.1.4 on 2021-02-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210124_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deleted_on',
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='deleted_on',
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
    ]
