# Generated by Django 3.1.3 on 2020-11-29 19:32

from django.db import migrations, models
import django.db.models.deletion
import veems.common.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id',
                 veems.common.fields.ShortUUIDField(
                     default=veems.common.fields._default,
                     editable=False,
                     max_length=12,
                     primary_key=True,
                     serialize=False)),
                ('created_on',
                 models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_on',
                 models.DateTimeField(auto_now=True, db_index=True)),
                ('presigned_upload_url', models.URLField()),
                ('media_type', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['created_on'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TranscodeJob',
            fields=[
                ('id',
                 veems.common.fields.ShortUUIDField(
                     default=veems.common.fields._default,
                     editable=False,
                     max_length=12,
                     primary_key=True,
                     serialize=False)),
                ('created_on',
                 models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_on',
                 models.DateTimeField(auto_now=True, db_index=True)),
                ('profile', models.CharField(max_length=100)),
                ('executor', models.CharField(max_length=20)),
                ('status',
                 models.CharField(choices=[('created', 'created'),
                                           ('processing', 'processing'),
                                           ('completed', 'completed'),
                                           ('failed', 'failed')],
                                  max_length=10)),
                ('started_on', models.DateTimeField(db_index=True)),
                ('ended_on', models.DateTimeField(db_index=True)),
                ('upload',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='media.upload')),
            ],
            options={
                'ordering': ['created_on'],
                'abstract': False,
            },
        ),
    ]
