# Generated by Django 3.1.4 on 2021-01-24 11:38

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import veems.common.fields
import veems.media.models
import veems.media.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', veems.common.fields.ShortUUIDField(default=veems.common.fields._default, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_on', models.DateTimeField(db_index=True, null=True)),
                ('presigned_upload_url', models.URLField(max_length=1000)),
                ('media_type', models.CharField(max_length=500)),
                ('file', models.FileField(storage=veems.media.storage_backends.MediaStorage, upload_to=veems.media.models._upload_file_upload_to)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('completed', 'completed')], db_index=True, default='draft', max_length=10)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='channel.channel')),
            ],
            options={
                'ordering': ['created_on'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', veems.common.fields.ShortUUIDField(default=veems.common.fields._default, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_on', models.DateTimeField(db_index=True, null=True)),
                ('title', models.CharField(max_length=500)),
                ('visibility', models.CharField(choices=[('private', 'private'), ('public', 'public'), ('unlisted', 'unlisted')], db_index=True, default='public', max_length=10)),
                ('is_viewable', models.BooleanField(db_index=True, default=False)),
                ('description', models.TextField(max_length=5000, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), null=True, size=None)),
                ('framerate', models.IntegerField(null=True)),
                ('duration', models.IntegerField(default=0, null=True)),
                ('custom_thumbnail_image', models.ImageField(blank=True, null=True, storage=veems.media.storage_backends.MediaStorage, upload_to=veems.media.models._video_custom_thumbnail_image_upload_to)),
                ('default_thumbnail_image', models.ImageField(blank=True, null=True, storage=veems.media.storage_backends.MediaStorage, upload_to=veems.media.models._video_default_thumbnail_image_upload_to)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='channel.channel')),
                ('upload', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.upload')),
            ],
            options={
                'ordering': ['created_on'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoRendition',
            fields=[
                ('id', veems.common.fields.ShortUUIDField(default=veems.common.fields._default, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_on', models.DateTimeField(db_index=True, null=True)),
                ('file', models.FileField(storage=veems.media.storage_backends.MediaStorage, upload_to=veems.media.models._video_rendition_upload_to)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('framerate', models.IntegerField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=30)),
                ('ext', models.CharField(max_length=4)),
                ('audio_codec', models.CharField(max_length=50, null=True)),
                ('video_codec', models.CharField(max_length=50, null=True)),
                ('container', models.CharField(max_length=30, null=True)),
                ('codecs_string', models.CharField(max_length=100, null=True)),
                ('file_size', models.IntegerField()),
                ('metadata', models.JSONField(null=True)),
                ('playlist_file', models.FileField(storage=veems.media.storage_backends.MediaStorage, upload_to=veems.media.models._video_rendition_playlist_file_upload_to)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.video')),
            ],
            options={
                'ordering': ['created_on'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoRenditionThumbnail',
            fields=[
                ('id', veems.common.fields.ShortUUIDField(default=veems.common.fields._default, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_on', models.DateTimeField(db_index=True, null=True)),
                ('file', models.FileField(storage=veems.media.storage_backends.MediaStorage, upload_to=veems.media.models._video_rendition_thumbnail_upload_to)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('time_offset_secs', models.IntegerField(null=True)),
                ('ext', models.CharField(max_length=4)),
                ('video_rendition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.videorendition')),
            ],
            options={
                'ordering': ['created_on'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TranscodeJob',
            fields=[
                ('id', veems.common.fields.ShortUUIDField(default=veems.common.fields._default, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_on', models.DateTimeField(db_index=True, null=True)),
                ('profile', models.CharField(max_length=100)),
                ('executor', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('created', 'created'), ('processing', 'processing'), ('completed', 'completed'), ('failed', 'failed')], db_index=True, max_length=10)),
                ('started_on', models.DateTimeField(db_index=True, null=True)),
                ('ended_on', models.DateTimeField(db_index=True, null=True)),
                ('failure_context', models.TextField(null=True)),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='media.video')),
            ],
            options={
                'ordering': ['created_on'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoRenditionSegment',
            fields=[
                ('id', veems.common.fields.ShortUUIDField(default=veems.common.fields._default, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_on', models.DateTimeField(db_index=True, null=True)),
                ('file', models.FileField(storage=veems.media.storage_backends.MediaStoragePublic, upload_to=veems.media.models._video_rendition_segment_upload_to)),
                ('segment_number', models.IntegerField()),
                ('video_rendition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.videorendition')),
            ],
            options={
                'unique_together': {('video_rendition', 'segment_number')},
            },
        ),
    ]
