# Generated by Django 3.1.3 on 2020-11-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcodejob',
            name='ended_on',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='transcodejob',
            name='started_on',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
