# Generated by Django 3.1.3 on 2020-12-05 20:24

from django.db import migrations, models
import django.db.models.deletion
import veems.common.fields
import veems.media.models
import veems.media.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFileThumbnail',
            fields=[
                (
                    'id',
                    veems.common.fields.ShortUUIDField(
                        default=veems.common.fields._default,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False
                    )
                ),
                (
                    'created_on',
                    models.DateTimeField(auto_now_add=True, db_index=True)
                ),
                (
                    'modified_on',
                    models.DateTimeField(auto_now=True, db_index=True)
                ),
                (
                    'file',
                    models.FileField(
                        storage=veems.media.storage_backends.
                        MediaFileThumbnailStorage,
                        upload_to=veems.media.models.
                        _media_file_thumbnail_upload_to
                    )
                ),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('ext', models.CharField(max_length=4)),
                (
                    'media_file',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='media.mediafile'
                    )
                ),
            ],
            options={
                'ordering': ['created_on'],
                'abstract': False,
            },
        ),
    ]
