# Generated by Django 3.1.4 on 2020-12-20 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediafile',
            old_name='hls_playlist_file',
            new_name='playlist_file',
        ),
    ]
