# Generated by Django 3.1.4 on 2020-12-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20201220_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='media_type',
            field=models.CharField(max_length=500),
        ),
    ]
