# Generated by Django 3.1.3 on 2020-12-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20201129_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='file',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
