# Generated by Django 3.1.4 on 2020-12-17 21:30

from django.db import migrations, models
import veems.media.models
import veems.media.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_medafilesegment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='hls_playlist',
        ),
        migrations.AddField(
            model_name='mediafile',
            name='hls_playlist_file',
            field=models.FileField(
                default=None,
                storage=veems.media.storage_backends.MediaFileStorage,
                upload_to=veems.media.models.
                _mediafile_hls_playlist_file_upload_to
            ),
            preserve_default=False,
        ),
    ]
