# Generated by Django 3.1.4 on 2020-12-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_auto_20201220_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='status',
            field=models.CharField(
                choices=[('draft', 'draft'), ('completed', 'completed')],
                default='draft',
                max_length=10,
            ),
        ),
    ]
