# Generated by Django 3.1.4 on 2021-01-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_auto_20210124_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolikedislike',
            name='is_like',
            field=models.BooleanField(db_index=True, null=True),
        ),
    ]
