# Generated by Django 3.1.3 on 2020-12-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_auto_20201206_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcodejob',
            name='failure_context',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
