# Generated by Django 3.1.4 on 2020-12-17 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_auto_20201217_2130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedaFileSegment',
            new_name='MediaFileSegment',
        ),
    ]
