# Generated by Django 3.1.4 on 2021-02-03 14:50

from django.db import migrations, models
import veems.media.models
import veems.media.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_auto_20210126_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcodejob',
            name='deleted_on',
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name='transcodejob',
            name='ended_on',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='transcodejob',
            name='failure_context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transcodejob',
            name='started_on',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='deleted_on',
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name='upload',
            name='presigned_upload_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='deleted_on',
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name='videolikedislike',
            name='deleted_on',
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name='videorendition',
            name='audio_codec',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='videorendition',
            name='codecs_string',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='videorendition',
            name='container',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='videorendition',
            name='deleted_on',
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name='videorendition',
            name='playlist_file',
            field=models.FileField(
                blank=True,
                null=True,
                storage=veems.media.storage_backends.MediaStorage,
                upload_to=veems.media.models._video_rendition_playlist_file_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name='videorendition',
            name='video_codec',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='videorenditionsegment',
            name='deleted_on',
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name='videorenditionthumbnail',
            name='deleted_on',
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
    ]
