# Generated by Django 3.1.4 on 2021-02-04 19:33

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import veems.media.models
import veems.media.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_auto_20210126_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcodejob',
            name='deleted_on',
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name='transcodejob',
            name='ended_on',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='transcodejob',
            name='failure_context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transcodejob',
            name='started_on',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='transcodejob',
            name='video',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='transcode_jobs',
                to='media.video',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upload',
            name='deleted_on',
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(
                blank=True,
                null=True,
                storage=veems.media.storage_backends.MediaStorage,
                upload_to=veems.media.models._upload_file_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name='upload',
            name='presigned_upload_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='deleted_on',
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='framerate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(max_length=1000),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='visibility',
            field=models.CharField(
                choices=[
                    ('draft', 'draft'),
                    ('private', 'private'),
                    ('public', 'public'),
                    ('unlisted', 'unlisted'),
                ],
                db_index=True,
                default='public',
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name='videolikedislike',
            name='deleted_on',
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name='videolikedislike',
            name='is_like',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='videorendition',
            name='audio_codec',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='videorendition',
            name='codecs_string',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='videorendition',
            name='container',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='videorendition',
            name='deleted_on',
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name='videorendition',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videorendition',
            name='framerate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videorendition',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videorendition',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videorendition',
            name='playlist_file',
            field=models.FileField(
                blank=True,
                null=True,
                storage=veems.media.storage_backends.MediaStorage,
                upload_to=veems.media.models._video_rendition_playlist_file_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name='videorendition',
            name='video',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='renditions',
                to='media.video',
            ),
        ),
        migrations.AlterField(
            model_name='videorendition',
            name='video_codec',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='videorendition',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videorenditionsegment',
            name='deleted_on',
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name='videorenditionsegment',
            name='video_rendition',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='rendition_segments',
                to='media.videorendition',
            ),
        ),
        migrations.AlterField(
            model_name='videorenditionthumbnail',
            name='deleted_on',
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name='videorenditionthumbnail',
            name='video_rendition',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='rendition_thumbnails',
                to='media.videorendition',
            ),
        ),
    ]
