# Generated by Django 3.1.4 on 2020-12-21 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_remove_video_playlist_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MediaFile',
            new_name='VideoRendition',
        ),
        migrations.RenameModel(
            old_name='MediaFileSegment',
            new_name='VideoRenditionSegment',
        ),
        migrations.RenameModel(
            old_name='MediaFileThumbnail',
            new_name='VideoRenditionThumbnail',
        ),
    ]
