# Generated by Django 3.1.6 on 2021-02-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_auto_20210204_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorendition',
            name='profile',
            field=models.CharField(
                choices=[
                    ('webm_144p', 'webm_144p'),
                    ('webm_240p', 'webm_240p'),
                    ('webm_360p', 'webm_360p'),
                    ('webm_360p_high', 'webm_360p_high'),
                    ('webm_720p', 'webm_720p'),
                    ('webm_720p_high', 'webm_720p_high'),
                    ('webm_1080p', 'webm_1080p'),
                    ('webm_1080p_high', 'webm_1080p_high'),
                    ('webm_1440p', 'webm_1440p'),
                    ('webm_1440p_high', 'webm_1440p_high'),
                    ('webm_2160p', 'webm_2160p'),
                    ('webm_2160p_high', 'webm_2160p_high'),
                ],
                default=None,
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transcodejob',
            name='profile',
            field=models.CharField(
                choices=[
                    ('webm_144p', 'webm_144p'),
                    ('webm_240p', 'webm_240p'),
                    ('webm_360p', 'webm_360p'),
                    ('webm_360p_high', 'webm_360p_high'),
                    ('webm_720p', 'webm_720p'),
                    ('webm_720p_high', 'webm_720p_high'),
                    ('webm_1080p', 'webm_1080p'),
                    ('webm_1080p_high', 'webm_1080p_high'),
                    ('webm_1440p', 'webm_1440p'),
                    ('webm_1440p_high', 'webm_1440p_high'),
                    ('webm_2160p', 'webm_2160p'),
                    ('webm_2160p_high', 'webm_2160p_high'),
                ],
                max_length=100,
            ),
        ),
    ]
