# Generated by Django 3.1.3 on 2020-12-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_auto_20201209_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='time_offset_secs',
            field=models.IntegerField(null=True),
        ),
    ]
