# Generated by Django 3.1.4 on 2020-12-19 11:40

from django.db import migrations, models
import veems.media.models
import veems.media.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_mediafile_codecs_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hls_playlist_file',
            field=models.FileField(
                default=None,
                storage=veems.media.storage_backends.MediaFileStorage,
                upload_to=veems.media.models._video_hls_playlist_file_upload_to
            ),
            preserve_default=False,
        ),
    ]
