# Generated by Django 3.1.3 on 2020-12-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_mediafile_time_offset_secs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='time_offset_secs',
        ),
        migrations.AddField(
            model_name='mediafilethumbnail',
            name='time_offset_secs',
            field=models.IntegerField(null=True),
        ),
    ]
