# Generated by Django 3.1.4 on 2021-02-03 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_auto_20210203_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcodejob',
            name='video',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='transcode_jobs',
                to='media.video',
            ),
        ),
        migrations.AlterField(
            model_name='videorendition',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videorendition',
            name='framerate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videorendition',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videorendition',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videorendition',
            name='video',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='renditions',
                to='media.video',
            ),
        ),
        migrations.AlterField(
            model_name='videorendition',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videorenditionsegment',
            name='video_rendition',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='rendition_segments',
                to='media.videorendition',
            ),
        ),
        migrations.AlterField(
            model_name='videorenditionthumbnail',
            name='video_rendition',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='rendition_thumbnails',
                to='media.videorendition',
            ),
        ),
    ]
