# Generated by Django 3.1.4 on 2020-12-21 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_auto_20201221_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videorenditionsegment',
            old_name='media_file',
            new_name='video_rendition',
        ),
        migrations.RenameField(
            model_name='videorenditionthumbnail',
            old_name='media_file',
            new_name='video_rendition',
        ),
        migrations.AlterUniqueTogether(
            name='videorenditionsegment',
            unique_together={('video_rendition', 'segment_number')},
        ),
    ]
