# Generated by Django 3.1.4 on 2021-02-03 22:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_auto_20210203_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(max_length=1000),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
