# Generated by Django 3.1.4 on 2020-12-28 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_auto_20201228_2004'),
        ('media', '0009_upload_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='channel',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to='channel.channel',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='channel',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to='channel.channel',
            ),
            preserve_default=False,
        ),
    ]
