# Generated by Django 3.1.4 on 2021-02-04 14:56

from django.db import migrations, models
import veems.media.models
import veems.media.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_auto_20210203_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(
                blank=True,
                null=True,
                storage=veems.media.storage_backends.MediaStorage,
                upload_to=veems.media.models._upload_file_upload_to,
            ),
        ),
    ]
