# Generated by Django 3.1.4 on 2021-01-02 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0005_auto_20210102_1703'),
        ('media', '0011_remove_upload_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='channel',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='uploads',
                to='channel.channel',
            ),
        ),
        migrations.AlterField(
            model_name='video',
            name='channel',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='videos',
                to='channel.channel',
            ),
        ),
    ]
