# Generated by Django 3.1.4 on 2021-02-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_auto_20210204_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolikedislike',
            name='is_like',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
    ]
