# Generated by Django 3.1.6 on 2021-02-20 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_upload_presigned_upload_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='presigned_upload_url',
        ),
    ]
