# Generated by Django 3.1.4 on 2021-02-04 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0012_auto_20210204_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcodejob',
            name='video',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='transcode_jobs',
                to='media.video',
            ),
            preserve_default=False,
        ),
    ]
