# Generated by Django 3.1.6 on 2021-02-23 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0012_remove_upload_presigned_upload_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcodejob',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='upload',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='videorendition',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='videorenditionthumbnail',
            options={'ordering': ['-created_on']},
        ),
    ]
