# Generated by Django 3.1.6 on 2021-03-16 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0015_auto_20210228_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='upload',
        ),
        migrations.AddField(
            model_name='upload',
            name='video',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='uploads',
                to='media.video',
            ),
        ),
    ]
