# Generated by Django 3.1.4 on 2021-01-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0015_auto_20210117_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_viewable',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='transcodejob',
            name='status',
            field=models.CharField(
                choices=[
                    ('created', 'created'),
                    ('processing', 'processing'),
                    ('completed', 'completed'),
                    ('failed', 'failed'),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name='upload',
            name='status',
            field=models.CharField(
                choices=[('draft', 'draft'), ('completed', 'completed')],
                db_index=True,
                default='draft',
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name='video',
            name='visibility',
            field=models.CharField(
                choices=[
                    ('private', 'private'),
                    ('public', 'public'),
                    ('unlisted', 'unlisted'),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
    ]
