# Generated by Django 3.1.6 on 2021-04-11 19:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0016_auto_20210316_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='presigned_upload_urls',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(max_length=500),
                default=list,
                size=None,
            ),
        ),
    ]
