# Generated by Django 3.1.4 on 2021-01-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0016_auto_20210117_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='visibility',
            field=models.CharField(
                choices=[
                    ('private', 'private'),
                    ('public', 'public'),
                    ('unlisted', 'unlisted'),
                ],
                db_index=True,
                default='public',
                max_length=10,
            ),
        ),
    ]
