# Generated by Django 3.1.4 on 2021-01-17 15:34

from django.db import migrations, models
import veems.media.models
import veems.media.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0017_auto_20210117_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_image',
            field=models.ImageField(
                blank=True,
                null=True,
                storage=veems.media.storage_backends.MediaStorage,
                upload_to=veems.media.models._video_thumbnail_image_upload_to,
            ),
        ),
    ]
