# Generated by Django 3.1.4 on 2021-01-17 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0018_video_thumbnail_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='thumbnail_image',
            new_name='default_thumbnail_image',
        ),
    ]
