# Generated by Django 3.1.4 on 2021-01-17 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0019_auto_20210117_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='upload',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='media.upload',
            ),
        ),
    ]
