# Generated by Django 3.1.4 on 2021-01-23 18:32

from django.db import migrations, models
import veems.media.models
import veems.media.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0020_auto_20210117_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='custom_thumbnail_image',
            field=models.ImageField(
                blank=True,
                null=True,
                storage=veems.media.storage_backends.MediaStorage,
                upload_to=(
                    veems.media.models._video_custom_thumbnail_image_upload_to
                ),
            ),
        ),
    ]
