# Generated by Django 3.1.4 on 2021-01-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0021_video_custom_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
