MAX_THUMBNAIL_HEIGHT = 720


def get_autogenerated_thumbnail_choices(video_record):
    """
    Return highest available thumbnail choices for a given video.
    """
    rendition = (
        video_record.renditions.filter(height__lte=MAX_THUMBNAIL_HEIGHT)
        .order_by('-height')
        .first()
    )
    if not rendition:
        return []

    thumbs = rendition.rendition_thumbnails.order_by('time_offset_secs')
    return thumbs
