/* ---- GLOBALS ---- */
export const SET_SESSION = 'SET_SESSION';

/* ---- CHANNELS ---- */
export const SET_ACTIVE_CHANNEL_ID = 'SET_ACTIVE_CHANNEL_ID';
export const SET_CHANNEL_SYNC_MODAL_OPEN = 'SET_CHANNEL_SYNC_MODAL_OPEN';
export const SET_CHANNELS = 'SET_CHANNELS';
export const SET_DB_STALE = 'SET_DB_STALE';
