/* ---- GLOBALS ---- */
export const CREATE_TOAST = 'CREATE_TOAST';
export const REMOVE_TOAST = 'REMOVE_TOAST';

/* ---- CHANNELS ---- */
export const SET_ACTIVE_CHANNEL_ID = 'SET_ACTIVE_CHANNEL_ID';
export const SET_CHANNEL_SYNC_MODAL_OPEN = 'SET_CHANNEL_SYNC_MODAL_OPEN';
export const SET_CHANNELS = 'SET_CHANNELS';

/* ---- CREATE CHANNEL FORM ---- */
export const SET_CREATE_CHANNEL_API_ERRORS = 'SET_CREATE_CHANNEL_API_ERRORS';
export const SET_CREATE_CHANNEL_SHOW_MODAL = 'SET_CREATE_CHANNEL_SHOW_MODAL';

/* ---- CHANNEL MANAGER ---- */
export const SET_ACTIVE_CHANNEL_VIDEOS = 'SET_ACTIVE_CHANNEL_VIDEOS';
export const SET_ACTIVE_CHANNEL_VIDEOS_LOADING = 'SET_ACTIVE_CHANNEL_VIDEOS_LOADING';

export const START_VIDEO_UPLOADING = 'START_VIDEO_UPLOADING';
export const SET_VIDEO_UPLOADING_FEEDBACK = 'SET_VIDEO_UPLOADING_FEEDBACK';

export const SET_ACTIVE_VIDEO_DETAIL_DATA = 'SET_ACTIVE_VIDEO_DETAIL_DATA';

export const SET_ACTIVE_VIDEO_DETAIL_FILE_SELECTOR_VISIBLE = 'SET_ACTIVE_VIDEO_DETAIL_FILE_SELECTOR_VISIBLE';
export const SET_VIDEO_DETAIL_MODAL_OPEN = 'SET_VIDEO_DETAIL_MODAL_OPEN';

/* ---- VIEW VIDEO PAGE ---- */
export const ADD_VIDEO_LIKE = 'ADD_VIDEO_LIKE';
export const ADD_VIDEO_DISLIKE = 'ADD_VIDEO_DISLIKE';
export const REMOVE_VIDEO_LIKE = 'REMOVE_VIDEO_LIKE';
export const REMOVE_VIDEO_DISLIKE = 'REMOVE_VIDEO_DISLIKE';
