/* ---- GLOBALS ---- */
export const SET_SESSION = 'SET_SESSION';
export const CREATE_TOAST = 'CREATE_TOAST';
export const REMOVE_TOAST = 'REMOVE_TOAST';

/* ---- CHANNELS ---- */
export const SET_ACTIVE_CHANNEL_ID = 'SET_ACTIVE_CHANNEL_ID';
export const SET_CHANNEL_SYNC_MODAL_OPEN = 'SET_CHANNEL_SYNC_MODAL_OPEN';
export const SET_CHANNELS = 'SET_CHANNELS';
export const SET_DB_STALE = 'SET_DB_STALE';

/* ---- CHANNEL MANAGER ---- */
export const SET_ACTIVE_CHANNEL_VIDEOS = 'SET_ACTIVE_CHANNEL_VIDEOS';
export const SET_ACTIVE_CHANNEL_VIDEOS_LOADING = 'SET_ACTIVE_CHANNEL_VIDEOS_LOADING';

export const START_VIDEO_UPLOADING = 'START_VIDEO_UPLOADING';
export const SET_VIDEO_UPLOADING_FEEDBACK = 'SET_VIDEO_UPLOADING_FEEDBACK';

export const SET_ACTIVE_VIDEO_DETAIL_DATA = 'SET_ACTIVE_VIDEO_DETAIL_DATA';

export const SET_ACTIVE_VIDEO_DETAIL_FILE_SELECTOR_VISIBLE = 'SET_ACTIVE_VIDEO_DETAIL_FILE_SELECTOR_VISIBLE';
export const SET_VIDEO_DETAIL_MODAL_OPEN = 'SET_VIDEO_DETAIL_MODAL_OPEN';
