from random import randint


def earnings():
    return f'${randint(10, 500)}.{randint(10,50)}'


CHANNEL_SYNCS = [
    {
        'veems_channel_name': 'SunlessKhan',
        'channel_name': 'SunlessKhan',
        'subscribers': '10K',
        'videos': 46,
        'videos_synced': 12,
        'last_sync': '2 days ago',
        'status': 'check_circle',
        'status_class': 'text-success',
    },
    {
        'veems_channel_name': 'TimCast',
        'channel_name': 'TimCast',
        'subscribers': '1.06M',
        'videos': 187,
        'videos_synced': 0,
        'last_sync': '—',
        'status': 'cached',
        'status_class': 'text-info',
    },
]

VIDEOS = [
    {
        'video_title': 'Marathon Day Is Here | How ToBe Behzinga',
        'video_thumb_url': 'https://i.ytimg.com/vi/pJkgymyv0_s/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCfMf5cCfG3GSPEB1LkYOuXFvgkOw',
        'views': '472K',
        'posted_on': '2 hours',
        'channel_name': 'Behzinga',
        'video_duration': '8:32',
        'type': '',
        'earnings': earnings(),
    },
    {
        'video_title': 'Megalovania on church organ',
        'video_thumb_url': None,
        'views': '30M',
        'posted_on': '1 year',
        'channel_name': 'Komp15',
        'video_duration': '1:14',
        'type': '',
        'earnings': earnings(),
        'status': 'public',
    },
    {
        'video_title': 'FREAKY TALENTED GUYS JUMP INTO "SOMEONE LIKE YOU" – (PIANO...',
        'video_thumb_url': 'https://i.ytimg.com/vi/UtEB1pFE8SI/hqdefault.jpg?sqp=-oaymwEZCOADEI4CSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCwqjdpaCGxOhOANLKHDDPmFI0zDQ',
        'views': '350K',
        'posted_on': '1 month',
        'channel_name': 'Thomas Krüger – Mr. Pianoman',
        'video_duration': '8:32',
        'type': '',
        'earnings': earnings(),
    },
    {
        'video_title': 'Return Home',
        'video_thumb_url': 'https://i.ytimg.com/vi/6_6zwVNn88o/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLB5qSDjiDCO-z3FngWzYAiz7zy7wQ',
        'views': '2M',
        'posted_on': '1 day',
        'channel_name': 'Jordan B Peterson',
        'video_duration': '8:32',
        'type': '',
        'earnings': earnings(),
    },
    {
        'video_title': 'BORAT 2 Official Trailer (2020) Sacha Baron Cohen, Comedy Movie HD',
        'video_thumb_url': 'https://i.ytimg.com/vi/JvPTCvUnNQA/hq720.jpg?sqp=-oaymwEZCNAFEJQDSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBD8uqhfYEzMrt1oUyl5S8sJqBKyQ',
        'views': '7.6M',
        'posted_on': '2 weeks',
        'channel_name': 'ONE Media',
        'video_duration': '3:13',
        'type': '',
        'earnings': earnings(),
    },
    {
        'video_title': 'iPhone 12 Unboxing Experience + MagSafe Demo!',
        'video_thumb_url': 'https://i.ytimg.com/vi/Sx6dAx7dnXg/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBPcBB-xQW6ME9EZ_hHCamT94QKKw',
        'views': '7.5M',
        'posted_on': '1 day',
        'channel_name': 'Marques Brownlee',
        'video_duration': '11:28',
        'type': '',
        'earnings': earnings(),
    },
    {
        'video_title': '🌧️ 𝘢𝘨𝘰𝘳𝘢𝘱𝘩𝘰𝘣𝘪𝘤 🌧️',
        'video_thumb_url': 'https://i.ytimg.com/vi/ra-XCs6LHAM/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAhgatDNbPPY2zZQYY6WXyiYI6vYw',
        'views': '1M',
        'posted_on': '2 days',
        'channel_name': 'CORPSE',
        'video_duration': '2:09',
        'type': '',
        'earnings': earnings(),
    },
    {
        'video_title': 'GIANT Pumpkin Carving Contest',
        'video_thumb_url': 'https://i.ytimg.com/vi/4CqwkiaXEOQ/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCo08PsPfQN-t2NXoDbjQL_fN6TBw',
        'views': '8.4M',
        'posted_on': '1 day',
        'channel_name': 'Dude Perfect',
        'video_duration': '23:49',
        'type': '',
        'earnings': earnings(),
    },
    {
        'video_title': 'Destiny 2 – Beyond Light – Story Reveal Trailer',
        'video_thumb_url': 'https://i.ytimg.com/vi/k6c6M0rKW7s/hq720.jpg?sqp=-oaymwEZCOgCEMoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDNCrsoH9ERgbgYfMznRQ8-kMfn5A',
        'views': '700K',
        'posted_on': '2 days',
        'channel_name': 'destinygame',
        'video_duration': '2:11',
        'type': '',
        'earnings': earnings(),
    },
    {
        'video_title': 'What if The Rookie Talked in Halo 3: ODST? (Parody)',
        'video_thumb_url': 'https://i.ytimg.com/vi/MZu8JVuAZD4/hq720.jpg?sqp=-oaymwEZCOgCEMoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBVuvJJK0c8qFgcMe6BhSJTI3DBcw',
        'views': '5K',
        'posted_on': '1 day',
        'channel_name': 'Press Start To Laugh',
        'video_duration': '19:58',
        'type': '',
        'earnings': earnings(),
    },
    {
        'video_title': 'Halo 4 on PC is Astonishing..',
        'video_thumb_url': 'https://i.ytimg.com/vi/eV0dI2ZR03Y/hq720.jpg?sqp=-oaymwEZCOgCEMoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAnnd6GZ4dBsSEg06D-i-oP0Ojipg',
        'views': '2.9K',
        'posted_on': '1 hour',
        'channel_name': 'UberNick',
        'video_duration': '8:57',
        'type': '',
        'earnings': earnings(),
    },
    {
        'video_title': "WORLD'S FASTEST ONBOARD: SSC Tuatara hits crazy 331mph top speed! | Top Gear",
        'video_thumb_url': 'https://i.ytimg.com/vi/N22JfNHiC1k/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDFZBZul3kmL5NgdzaVfmvu87kNwg',
        'views': '4M',
        'posted_on': '2 days',
        'channel_name': 'Top Gear',
        'video_duration': '2:05',
        'type': '',
        'earnings': earnings(),
    },
    {
        'video_title': 'I BOUGHT 4 HOUSES & 5 CARS THEN QUIT MY JOB...',
        'video_thumb_url': 'https://i.ytimg.com/vi/f9jWy35kp68/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDq7CyYtXT9-gIDk0h0yKp6yRYiIQ',
        'views': '126K',
        'posted_on': '1 day',
        'channel_name': 'Mat Armstrong',
        'video_duration': '13:11',
        'type': '',
        'earnings': earnings(),
    },
    {
        'video_title': 'Architects - "Animals"',
        'video_thumb_url': 'https://i.ytimg.com/vi/jdWhJcrrjQs/hq720.jpg?sqp=-oaymwEZCOgCEMoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCXDn9QqmPKSzQZS1a8UtkrY6UgrA',
        'views': '489K',
        'posted_on': '2 days',
        'channel_name': 'Epitaph Records',
        'video_duration': '4:04',
        'type': '',
        'earnings': earnings(),
    },
    {
        'video_title': 'The Supernova That Measured The Universe',
        'video_thumb_url': 'https://i.ytimg.com/vi/ljoeOLuX6Z4/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAD4r1xAJWJp7X-D91Oic2uFA6Lew',
        'views': '661K',
        'posted_on': '2 days',
        'channel_name': 'Veritasium',
        'video_duration': '13:41',
        'type': '',
        'earnings': earnings(),
    },
    {
        'video_title': 'Stray Kids 『ALL IN』 Music Video',
        'video_thumb_url': 'https://i.ytimg.com/vi/ySxIjeCScgY/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBzJv4224PXukyw4bKIfm6KP0Lc3w',
        'views': '2.5M',
        'posted_on': '2 days',
        'channel_name': 'Stray Kids Japan official',
        'video_duration': '3:14',
        'type': '',
        'earnings': earnings(),
    },
    {
        'video_title': 'MY FIRST BILLBOARD MUSIC AWARDS!!!!! | Addison Rae',
        'video_thumb_url': 'https://i.ytimg.com/vi/aFn5NVuNqvI/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAXif6YdQnxg-Cq2xjXeZIls2tJnA',
        'views': '3.1M',
        'posted_on': '2 days',
        'channel_name': 'Addison Rae',
        'video_duration': '5:37',
        'type': '',
        'earnings': earnings(),
    },
    {
        'video_title': 'Minecraft Mob Hunt...',
        'video_thumb_url': 'https://i.ytimg.com/vi/pQW_S0Y16us/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBzzYKDmq1pkOBVeVVZ98rBuPPbCw',
        'views': '2.5M',
        'posted_on': '5 days',
        'channel_name': 'GeorgeNotFound',
        'video_duration': '24:09:00',
        'type': 'gaming',
    },
    {
        'video_title': 'TommyInnit Speaks To PewDiePie...',
        'video_thumb_url': 'https://i.ytimg.com/vi/3Ect8Nl3rZw/hqdefault.jpg?sqp=-oaymwEYCKgBEF5IVfKriqkDCwgBFQAAiEIYAXAB&rs=AOn4CLDmESwD5vAy8P2i4BdQX6vqi9SEgA',
        'views': '455K',
        'posted_on': '3 days',
        'channel_name': 'TommyVODS',
        'video_duration': '52:05:00',
        'type': 'gaming',
    },
    {
        'video_title': 'Please Click.. THERE IS A GAME!',
        'video_thumb_url': 'https://i.ytimg.com/vi/UqzZD2Ggnu4/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAmxPwXILaXlAzLR44jnxWIG-QhSw',
        'views': '1M',
        'posted_on': '1 day',
        'channel_name': 'DanTDM',
        'video_duration': '1:25:05',
        'type': 'gaming',
    },
    {
        'video_title': 'Talking Tom Gold Run Android Gameplay - Talking...',
        'video_thumb_url': 'https://i.ytimg.com/vi/TtjIMhdCQtA/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDc5qONBsCXl12AM2Bn1BnjgqvHxA',
        'views': '48K',
        'posted_on': '2 hours',
        'channel_name': 'Jabed Clerks Gaming',
        'video_duration': '15:45',
        'type': 'gaming',
    },
    {
        'video_title': 'Productivity Tips From Tim Ferriss',
        'video_thumb_url': 'https://i.ytimg.com/vi/TrvLEgPpV8s/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLB2M5YIH9DFA3szEifIOl8MF3WMUg',
        'views': '78K',
        'posted_on': '3 hours',
        'channel_name': 'Tim Ferriss',
        'video_duration': '6:34',
        'type': 'learning',
    },
    {
        'video_title': 'The search for life on Mars | Natural History Museum',
        'video_thumb_url': 'https://i.ytimg.com/vi/GHm8VKhI6i4/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCpck_hZHWitkS_LPFPhnUoi6pgDQ',
        'views': '15K',
        'posted_on': '2 years',
        'channel_name': 'Natural History Museum',
        'video_duration': '11:21',
        'type': 'learning',
    },
    {
        'video_title': '#StayHome and Learn About Henry VIII with Suzannah...',
        'video_thumb_url': 'https://i.ytimg.com/vi/33G-8TJ9CJ0/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDeiQ_6UciT1pudJ44rdFHTK0IVtA',
        'views': '47K',
        'posted_on': '1 week',
        'channel_name': 'Timeline - World History Documentaries',
        'video_duration': '45:28:00',
        'type': 'learning',
    },
    {
        'video_title': 'AQA English Language Paper 1 Question 2 (updated &...',
        'video_thumb_url': 'https://i.ytimg.com/vi/L_dE68iUg-k/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBFKncFgpX07WasRQtFnMizzUIG2A',
        'views': '408K',
        'posted_on': '1 year',
        'channel_name': 'Mr Bruff',
        'video_duration': '5:33',
        'type': 'learning',
    },
    {
        'video_title': 'chief. - Time Remembered',
        'video_thumb_url': 'https://i.ytimg.com/vi/v_LPm6P-du4/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCmdkJHB_V2nCUGLvTvZAUAMIXEEQ',
        'views': '55K',
        'posted_on': '3 days',
        'channel_name': 'ChilledCow',
        'video_duration': '19:40',
        'type': 'music',
    },
    {
        'video_title': 'NOGA EREZ LIVE — Performing Recent Singles...',
        'video_thumb_url': 'https://i.ytimg.com/vi/xRikKpW9Ss8/hqdefault.jpg?sqp=-oaymwEZCPYBEIoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLANoxY-oFZ4qN90LTxSB6OHaW_oYA',
        'views': '18K',
        'posted_on': '1 day',
        'channel_name': 'Noga Erez',
        'video_duration': '1:04:25',
        'type': 'music',
    },
    {
        'video_title': '4 basic chords, 22 songs on ukulele',
        'video_thumb_url': 'https://i.ytimg.com/vi/lq-_NPP4CTs/hq720.jpg?sqp=-oaymwEZCOgCEMoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAuWvifCr37K-CL1m2kemTu21Dzqw',
        'views': '816K',
        'posted_on': '4 months',
        'channel_name': 'Elise Ecklund',
        'video_duration': '8:56',
        'type': 'music',
    },
    {
        'video_title': 'Tenacious D - Tribute (Video)',
        'video_thumb_url': 'https://i.ytimg.com/vi/_lK4cX5xGiQ/hq720.jpg?sqp=-oaymwEZCOgCEMoBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLDMKYksMGs4Y5KIYl8fSmeeSTawsA',
        'views': '89M',
        'posted_on': '2 years',
        'channel_name': 'Tenacious D',
        'video_duration': '4:53',
        'type': 'music',
    },
]
